# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bbcb0c9273f22ac95ee9ab7f1c10f732170719a8c5ce0e701d3cb81fc7193942ec67b6dac9b833ee38ccb5a9326d791741a76b1178a31ef07869bbc907d26e1

test:
  secret_key_base: 85e2476610753ff1c0088e63f2ba73381abf0d59604ee57f49bd37fee7135912e8231eaaddf44a08e70931b1cb841fce4f43356aa592774c11b27658172d7c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
